defmodule AiroWeb.Layouts do
  @moduledoc """
  Layouts for AiroWeb. Generated by `mix joby_kit.new`.

  Pages compose `<Layouts.app flash={@flash}>...` from inside their
  LiveView render. The app shell nav and the kit's `flash_group` are
  wired in here so every page gets them for free.
  """
  use AiroWeb, :html

  embed_templates "layouts/*"

  attr :flash, :map, required: true
  attr :current_scope, :map, default: nil
  attr :active_nav, :string, default: nil
  slot :inner_block, required: true

  def app(assigns) do
    assigns =
      assign(assigns, :nav_links, [
        %{key: "models", label: "Models", href: "/admin/models"},
        %{key: "providers", label: "Providers", href: "/admin/providers"},
        %{key: "deployments", label: "Deployments", href: "/admin/deployments"},
        %{key: "aliases", label: "Aliases", href: "/admin/aliases"},
        %{key: "keys", label: "Keys", href: "/admin/keys"},
        %{key: "usage", label: "Usage", href: "/admin/usage"},
        %{key: "logs", label: "Logs", href: "/admin/logs"},
        %{key: "docs", label: "Docs", href: "/docs"}
      ])

    ~H"""
    <div class="relative flex min-h-dvh flex-col bg-base-100">
      <div class="sticky top-0 z-40 border-b border-base-300 bg-base-100 shadow-sm">
        <nav
          data-app-shell="nav"
          class="mx-auto flex min-h-16 w-full max-w-7xl items-center justify-between gap-8 px-6"
          aria-label="Primary"
        >
          <.link
            navigate={~p"/"}
            class="shrink-0 text-lg font-semibold tracking-tight text-base-content transition-colors hover:text-base-content/80"
          >
            Airo
          </.link>
          <ul class="flex min-w-0 items-center gap-1 overflow-x-auto py-3">
            <li :for={link <- @nav_links} class="shrink-0">
              <.link
                navigate={link.href}
                class={[
                  "block rounded-lg px-3 py-2 text-sm font-medium transition-colors",
                  @active_nav == link.key &&
                    "bg-primary/15 text-base-content shadow-sm ring-1 ring-primary/10",
                  @active_nav != link.key &&
                    "text-base-content/75 hover:bg-base-200 hover:text-base-content"
                ]}
              >
                {link.label}
              </.link>
            </li>
          </ul>
        </nav>
      </div>

      <main class="flex-1">
        {render_slot(@inner_block)}
      </main>

      <footer class="mt-12 border-t border-base-300/60">
        <div class="mx-auto flex max-w-7xl flex-col gap-3 px-6 py-6 text-xs text-base-content/60 sm:flex-row sm:items-center sm:justify-between">
          <p>
            Airo · powered by
            <a
              href="https://github.com/jobycorp/joby_kit"
              class="link link-hover font-medium"
              target="_blank"
              rel="noopener"
            >
              JobyKit
            </a>
          </p>
          <p class="font-mono">
            <a href="/design" class="link link-hover">/design</a>
            <span class="opacity-40"> · </span>
            <a href="/custom-designs" class="link link-hover">/custom-designs</a>
            <span class="opacity-40"> · </span>
            <a href="/design.json" class="link link-hover">/design.json</a>
          </p>
        </div>
      </footer>

      <JobyKit.CoreComponents.flash_group flash={@flash} />
    </div>
    """
  end
end
