import Config

# Configure your database
config :airo, Airo.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "airo_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# Cloak vault key for development. Static, non-secret — fine to check in;
# prod loads its key from CLOAK_KEY in config/runtime.exs.
config :airo, Airo.Vault,
  ciphers: [
    default:
      {Cloak.Ciphers.AES.GCM,
       tag: "AES.GCM.V1",
       key: Base.decode64!("b5UUYJgkw/cqtMnACosv+GGqgr9U1WnlSLnzGGSEFvQ="),
       iv_length: 12}
  ]

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
# Loopback by default. `AIRO_DEV_BIND=lan` binds every interface so the fleet's
# agents can reach a dev airo as an *observer* (S26,
# DESIGN-agent-lifecycle-and-roles.md §2) — they then use the workstation's LAN
# name as an `AIRO_OBSERVER_SOCKET_URLS` entry. Opt-in, never the default: a dev
# airo on the LAN has no socket token, same as prod today. For a workstation
# that should always bind the LAN, put the override in the gitignored
# `config/dev.local.exs` (imported at the bottom of this file) instead of
# remembering the env var on every restart.
dev_bind =
  case System.get_env("AIRO_DEV_BIND") do
    "lan" -> {0, 0, 0, 0}
    _loopback -> {127, 0, 0, 1}
  end

config :airo, AiroWeb.Endpoint,
  http: [ip: dev_bind],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "qZnkRROOtPmzor7YVCyXhSC6ZTQEKwk4k8KW7cL/SHoja8UFj+s5tK8tZ4Xc4tal",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:airo, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:airo, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :airo, AiroWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/airo_web/router\.ex$"E,
      ~r"lib/airo_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :airo, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# The local ONNX routing classifier (S15) loads at boot in every environment —
# see `config :airo, Airo.Routing.LocalClassifier` in config/config.exs.

# Per-workstation overrides, gitignored — e.g. the LAN bind above:
#
#     config :airo, AiroWeb.Endpoint, http: [ip: {0, 0, 0, 0}]
#
# Imported last so it wins over everything in this file.
if File.exists?(Path.expand("dev.local.exs", __DIR__)), do: import_config("dev.local.exs")
